s<-read.csv(file="C:/Users/Julia/Desktop/heart.csv", header=FALSE, skip=1)
years<-as.vector(s$V1)
m<-mean(years)
std<-sd(years)
hi<-hist(years,  col = "lightblue", main = "Heart disase")
hist(years,  col = "lightblue", main = "Heart disase")
curve(dnorm(x, mean=m, sd=std)*length(years)*(hi$breaks[2]-hi$breaks[1]), col="darkblue", lwd=2, add=TRUE, yaxt="n")
hi<-hist(years, breaks= 3.5*sd(years)* n^(-(1/3)), col = "lightblue", main = "Heart disase")
hist(years, breaks= 3.5*sd(years)*n^(-(1/3)), col = "lightblue", main = "Heart disase")
curve(dnorm(x, mean=m, sd=std)*length(years)*(hi$breaks[2]-hi$breaks[1]), col="darkblue", lwd=2, add=TRUE, yaxt="n")
hi<-hist(years, breaks= 2*IQR(years)*(length(years))^(-(1/3)), col = "lightblue", main = "Heart disase")
hist(years, breaks= 2*IQR(years)*(length(years))^(-(1/3)), col = "lightblue", main = "Heart disase")
curve(dnorm(x, mean=m, sd=std)*length(years)*(hi$breaks[2]-hi$breaks[1]), col="darkblue", lwd=2, add=TRUE, yaxt="n")

n<-100
years <- rnorm(n)

plot(pnorm(sort(years)),(1:length(years))/length(years),asp=1, ylab="Empirical P", xlab="Theoretical P", main = "Normal P-P Plot")
abline(0,1,col=2)
qqnorm(years)
qqline(years)
shapiro.test(years)
#ks.test(years, pnorm)
install.packages("nortest")
library(nortest)
pearson.test(years)
